stages:
  - test

mapping-data-is-sorted:
  image: ubuntu:latest
  stage: test
  variables:
    LANG: en_US.UTF-8
  script:
    - bash -c 'diff <(grep \{ mapping_data.toml) <(sort -u mapping_data.toml | grep \{)'
